# Generated by Django 3.2.7 on 2021-11-20 19:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=30)),
                ('customer_last_name', models.CharField(max_length=30)),
                ('shipping_address', models.CharField(max_length=60)),
                ('billing_address', models.CharField(max_length=60)),
                ('customer_status', models.CharField(choices=[('PREFFERED', 'preferred'), ('OKAY', 'okay'), ('SHAKY', 'shaky')], default='PREFERRED', max_length=30)),
            ],
            options={
                'verbose_name': 'Customer Information',
                'verbose_name_plural': 'Customer Information',
            },
        ),
        migrations.CreateModel(
            name='orderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half_Pint_Count', models.IntegerField(default=0)),
                ('one_Quart_Count', models.IntegerField(default=0)),
                ('pint_Count', models.IntegerField(default=0)),
                ('half_Gallon_Count', models.IntegerField(default=0)),
                ('gallon_Count', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orderentry.customerinfo')),
                ('order_Item_Flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
            options={
                'verbose_name': 'Order Information',
                'verbose_name_plural': 'Order Information',
            },
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this invoice', primary_key=True, serialize=False)),
                ('order_Item_Shipping', models.CharField(choices=[('STANDARD', 'standard'), ('EXPEDITED', 'expedited'), ('2-DAY', '2-day')], default='STANDARD', max_length=20)),
                ('order_date', models.DateTimeField(verbose_name='order date')),
                ('total_Cost', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderentry.customerinfo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderentry.orderinfo')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
    ]
