# Generated by Django 3.2.7 on 2021-10-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('shipping_address', models.CharField(max_length=60)),
                ('billing_address', models.CharField(max_length=60)),
                ('customer_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='orderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_Item_Flavor', models.CharField(max_length=20)),
                ('order_Item_Size', models.CharField(max_length=20)),
                ('order_Item_Quantity', models.IntegerField(default=0)),
                ('order_Item_Shipping', models.CharField(max_length=20)),
                ('order_date', models.DateTimeField(verbose_name='order date')),
                ('total_Cost', models.IntegerField(default=0)),
            ],
        ),
    ]
