# Generated by Django 3.2.7 on 2021-11-20 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('orderentry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_Item_Flavor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.flavor'),
        ),
    ]
