# Generated by Django 3.2.7 on 2021-10-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderentry', '0003_remove_customerinfo_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='customer_status',
            field=models.CharField(choices=[('PREFFERED', 'preferred'), ('OKAY', 'okay'), ('SHAKY', 'shaky')], default='PREFERRED', max_length=30),
        ),
    ]
