# Generated by Django 3.2.7 on 2021-10-07 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_itemflavor_item_flavor'),
        ('orderentry', '0004_customerinfo_customer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='order_Item_Quantity',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='order_Item_Size',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='order_Size_Quantity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.sizecounts'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_Item_Flavor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.itemflavor'),
        ),
    ]
