# Generated by Django 3.2.7 on 2021-10-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderentry', '0005_auto_20211007_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_Item_Shipping',
            field=models.CharField(choices=[('STANDARD', 'standard'), ('EXPEDITED', 'expedited'), ('2-DAY', '2-day')], default='STANDARD', max_length=20),
        ),
    ]
