# Generated by Django 3.2.7 on 2021-10-11 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderentry', '0006_alter_orderinfo_order_item_shipping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerinfo',
            options={'verbose_name': 'Customer Information', 'verbose_name_plural': 'Customer Information'},
        ),
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'verbose_name': 'Order Information', 'verbose_name_plural': 'Order Information'},
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='order',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='orderentry.orderinfo'),
        ),
    ]
