# Generated by Django 3.2.7 on 2021-10-11 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderentry', '0008_auto_20211011_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='order',
        ),
    ]
