# Generated by Django 3.2.7 on 2021-10-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderentry', '0009_remove_customerinfo_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='order_Size_Quantity',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='chocolateQuantity',
            field=models.IntegerField(default=0),
        ),
    ]
