# Generated by Django 3.2.7 on 2021-10-14 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20211014_1844'),
        ('orderentry', '0010_auto_20211011_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='chocolateQuantity',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='order_Size_Quantity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.sizecounts'),
        ),
    ]
