# Generated by Django 3.2.7 on 2021-10-20 04:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orderentry', '0011_auto_20211014_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orderentry.customerinfo'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this invoice', primary_key=True, serialize=False),
        ),
    ]
