# Generated by Django 3.2.7 on 2021-10-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderentry', '0012_auto_20211020_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='order_Size_Quantity',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='gallon_Count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='half_Gallon_Count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='half_Pint_Count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='one_Quart_Count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='pint_Count',
            field=models.IntegerField(default=0),
        ),
    ]
