# Generated by Django 3.2.7 on 2021-10-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderentry', '0013_auto_20211020_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total_Cost',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='total_Cost',
            field=models.IntegerField(default=0),
        ),
    ]
