# Generated by Django 3.2.7 on 2021-10-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderentry', '0014_auto_20211020_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='total_Cost',
            new_name='cost',
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_Cost',
            field=models.IntegerField(default=0),
        ),
    ]
