# Generated by Django 3.2.7 on 2021-10-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderentry', '0015_auto_20211020_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='customer_firstName',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='customer_lastName',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
