# Generated by Django 3.2.7 on 2021-10-24 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderentry', '0016_auto_20211024_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinfo',
            old_name='customer_firstName',
            new_name='customer_first_name',
        ),
        migrations.RenameField(
            model_name='customerinfo',
            old_name='customer_lastName',
            new_name='customer_last_name',
        ),
    ]
