# Generated by Django 3.2.7 on 2021-10-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderentry', '0017_auto_20211024_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='customer_first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='customer_last_name',
            field=models.CharField(max_length=30),
        ),
    ]
