# Generated by Django 3.2.7 on 2021-10-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmanage', '0002_alter_externalticket_ticket_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalticket',
            name='ticket_resolution_date',
            field=models.DateTimeField(null=True, verbose_name='Problem Resolved'),
        ),
        migrations.AlterField(
            model_name='internalticket',
            name='ticket_resolution_date',
            field=models.DateTimeField(null=True, verbose_name='Problem Resolved'),
        ),
    ]
