# Generated by Django 3.2.7 on 2021-10-05 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lastChangeMade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_Change_Made', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipts', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='sizeCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half_Pint_Count', models.IntegerField(default=30)),
                ('one_Quart_Count', models.IntegerField(default=30)),
                ('pint_Count', models.IntegerField(default=30)),
                ('half_Gallon_Count', models.IntegerField(default=30)),
                ('gallon_Count', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='toBeSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_Be_Sent', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='itemFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_Flavor', models.CharField(max_length=30)),
                ('item_Size_Quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sizecounts')),
            ],
        ),
    ]
