# Generated by Django 3.2.7 on 2021-11-20 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(choices=[('CHOCOLATE', 'chocolate'), ('VANILLA', 'vanilla'), ('COOKIESNCREME', 'cookiesncreme'), ('STRAWBERRY', 'strawberry')], max_length=100)),
            ],
            options={
                'verbose_name': 'Flavor',
                'verbose_name_plural': 'Flavors',
            },
        ),
        migrations.CreateModel(
            name='prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half_Pint_price', models.IntegerField(default=30)),
                ('one_Quart_price', models.IntegerField(default=30)),
                ('pint_price', models.IntegerField(default=30)),
                ('half_Gallon_price', models.IntegerField(default=30)),
                ('gallon_price', models.IntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.CreateModel(
            name='receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipts', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='sizeCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half_Pint_Count', models.IntegerField(default=30)),
                ('one_Quart_Count', models.IntegerField(default=30)),
                ('pint_Count', models.IntegerField(default=30)),
                ('half_Gallon_Count', models.IntegerField(default=30)),
                ('gallon_Count', models.IntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Size Count',
                'verbose_name_plural': 'Size Counts',
            },
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.flavor')),
                ('size_Counts', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.sizecounts')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
