# Generated by Django 3.2.7 on 2021-10-05 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemflavor',
            name='item_Flavor',
        ),
    ]
