# Generated by Django 3.2.7 on 2021-10-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_itemflavor_item_flavor'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemflavor',
            name='item_Flavor',
            field=models.CharField(default='Vanilla', max_length=100),
            preserve_default=False,
        ),
    ]
