# Generated by Django 3.2.7 on 2021-10-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_itemflavor_item_flavor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemflavor',
            name='item_Flavor',
            field=models.CharField(choices=[('CHOCOLATE', 'chocolate'), ('VANILLA', 'vanilla'), ('COOKIESNCREME', 'cookiesncreme'), ('STRAWBERRY', 'strawberry')], max_length=100),
        ),
    ]
