# Generated by Django 3.2.7 on 2021-10-11 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_itemflavor_item_flavor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='toBeSent',
        ),
    ]
