# Generated by Django 3.2.7 on 2021-10-11 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_delete_tobesent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemflavor',
            options={'verbose_name': 'Item Flavor', 'verbose_name_plural': 'Item Flavors'},
        ),
        migrations.AlterModelOptions(
            name='sizecounts',
            options={'verbose_name': 'Size Count', 'verbose_name_plural': 'Size Counts'},
        ),
    ]
