# Generated by Django 3.2.7 on 2021-10-11 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20211011_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemflavor',
            name='item_Size_Quantity',
        ),
        migrations.AddField(
            model_name='sizecounts',
            name='flavor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemflavor'),
        ),
    ]
