# Generated by Django 3.2.7 on 2021-10-14 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20211011_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizecounts',
            name='flavor',
        ),
        migrations.AddField(
            model_name='itemflavor',
            name='size_Counts',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.sizecounts'),
        ),
    ]
