# Generated by Django 3.2.7 on 2021-10-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderentry', '0011_auto_20211014_1844'),
        ('inventory', '0008_auto_20211014_1844'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='itemFlavor',
            new_name='item',
        ),
    ]
