# Generated by Django 3.2.7 on 2021-10-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_itemflavor_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AddField(
            model_name='sizecounts',
            name='item_Flavor',
            field=models.CharField(choices=[('CHOCOLATE', 'chocolate'), ('VANILLA', 'vanilla'), ('COOKIESNCREME', 'cookiesncreme'), ('STRAWBERRY', 'strawberry')], default='chocolate', max_length=100),
        ),
    ]
