# Generated by Django 3.2.7 on 2021-11-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shipmentTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingCode', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tracking Code',
            },
        ),
    ]
